"""
Clinical report generator.
Produces structured JSON and formatted clinical reports.
"""

import json
import uuid
from datetime import datetime
from pathlib import Path
from app.config import settings
from app.utils.logger import get_logger

report_logger = get_logger("report", "report.log")

DISCLAIMER = (
    "⚕️ DISCLAIMER: This report is generated by an AI-based Clinical Decision "
    "Support System for educational and research purposes only. It is NOT a "
    "substitute for professional medical advice, diagnosis, or treatment. "
    "Always seek the advice of a qualified healthcare provider."
)


class ReportGenerator:
    """Generates structured clinical reports from diagnosis results."""

    def __init__(self):
        self.output_dir = Path(settings.report_storage_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_json_output(self, safety_result: dict) -> dict:
        """Generate structured JSON output."""
        return {
            "report_id": str(uuid.uuid4()),
            "generated_at": datetime.utcnow().isoformat(),
            "system": "Multimodal Clinical Decision Support System",
            "version": "1.0.0",
            "diagnosis": {
                "primary": safety_result.get("primary_diagnosis", ""),
                "confidence": safety_result.get("combined_confidence", 0),
                "severity": safety_result.get("severity", "unknown"),
                "urgency": safety_result.get("urgency", "routine"),
            },
            "modality": safety_result.get("modality", "unknown"),
            "fusion_strategy": safety_result.get("fusion_strategy", ""),
            "safety": {
                "status": safety_result.get("safety_status", "unknown"),
                "is_approved": safety_result.get("is_approved", False),
                "risk_factors": safety_result.get("risk_factors", []),
                "message": safety_result.get("safety_message", ""),
            },
            "validation": {
                "guideline_consistent": safety_result.get("is_guideline_consistent", False),
                "support_score": safety_result.get("guideline_support_score", 0),
                "notes": safety_result.get("validation_notes", []),
            },
            "explanation": safety_result.get("explanation", ""),
            "recommended_actions": safety_result.get("recommended_actions", []),
            "disclaimer": DISCLAIMER,
        }

    def generate_clinical_report(self, safety_result: dict,
                                 symptoms: str = None,
                                 question: str = None) -> str:
        """Generate a formatted markdown clinical report and save to file."""
        report_id = str(uuid.uuid4())[:8]
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        primary = safety_result.get("primary_diagnosis", "N/A")
        confidence = safety_result.get("combined_confidence", 0)
        status = safety_result.get("safety_status", "unknown")
        explanation = safety_result.get("explanation", "")
        severity = safety_result.get("severity", "unknown")
        urgency = safety_result.get("urgency", "routine")

        status_icon = "✅" if status == "approved" else "⚠️"

        report = f"""# Clinical Decision Support Report
---
**Report ID:** {report_id}  
**Generated:** {timestamp}  
**System:** Multimodal Clinical Decision Support System v1.0

---

## Patient Input Summary

{"**Symptoms:** " + symptoms if symptoms else ""}
{"**Clinical Question:** " + question if question else ""}

---

## Diagnosis Result

| Field | Value |
|-------|-------|
| **Primary Diagnosis** | {primary} |
| **Confidence** | {confidence:.0%} |
| **Severity** | {severity.upper()} |
| **Urgency** | {urgency.upper()} |
| **Safety Status** | {status_icon} {status.upper()} |

---

## Clinical Explanation

{explanation}

---

## Safety Assessment

{safety_result.get("safety_message", "")}

### Risk Factors
"""
        for rf in safety_result.get("risk_factors", []):
            report += f"- {rf}\n"

        if not safety_result.get("risk_factors"):
            report += "- No significant risk factors identified\n"

        report += f"""
---

## Validation Notes
"""
        for note in safety_result.get("validation_notes", []):
            report += f"- {note}\n"

        report += f"""
---

## Recommended Actions
"""
        for action in safety_result.get("recommended_actions", []):
            report += f"1. {action}\n"

        report += f"""
---

> {DISCLAIMER}
"""

        # Save report
        filename = f"report_{report_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        filepath = self.output_dir / filename
        filepath.write_text(report, encoding="utf-8")
        report_logger.info(f"Report saved: {filepath}")

        return str(filepath)
